services:
  - type: web  # Define que é um serviço web
    name: agenda-flask  # Nome do serviço
    env: python  # Ambiente de execução
    buildCommand: ""  # Não há comando de build necessário para Flask
    startCommand: gunicorn -b 0.0.0.0:$PORT main:app  # Comando para iniciar a aplicação
    autoDeploy: true  # Permite que o serviço seja atualizado automaticamente após novos commits
    envVars:  # Configuração de variáveis de ambiente
      - key: FLASK_ENV
        value: production  # Define o ambiente como produção
    runtime: python3  # Versão do Python que será usada (especifique a versão se necessário, como python3.9)
